server:
  port: 8080
#  port: 8443
#  ssl:
#    key-alias: alias1
#    key-password: 123456
#    key-store: classpath:serverKeystore.jks
#    key-store-password: 123456
  tomcat:
    uri-encoding: UTF-8
druid1:
  url: jdbc:mysql://127.0.0.1:3306/sprssoZdemo1?useUnicode=true&characterEncoding=utf-8
  username: user1
  password: aaa
  driver-class: com.mysql.jdbc.Driver
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true
# spring:
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    sprssozdemo1.sprssoLogin: DEBUG
