server:
  port: 8083
#  ssl:
#    key-alias: alias1
#    key-password: 123456
#    key-store: classpath:serverKeystore.jks
#    key-store-password: 123456
##    key-store-provider: canOmit
##    key-store-type: canOmit
  tomcat:
    uri-encoding: UTF-8

security:
  oauth2:
    resource:
      jwt:
        keyUri: http://localhost:8080/oauth/token_key
        #keyUri: https://localhost:8443/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjWx7waAGOW0GCvWtz22C0r2S9IDpjpURZiUbX9DFgUBSJ2/XqHYWP3I/I8IAWIvLqaE4RFAAwzaIySVN/pM2WUVRPCHlRF192HtrAc3CoZD5lVOHsU5f++22N6CrjQJQkX4V88efI596TbzqYkNJzmNLeBKuip9MLlMTW6z7+wuIw3KOUGk3+nH8MspMUk7vrGFOZG+UslkYCnx6+1gInEddaZm5HHyvAUh/lo7At3a2g7TaYE3PepSpZsZ6YNw68YhOkI+xG2OFkLek1vej8bGz6wEubeYI4nI3fjm8pEqh1s0NJrHwrxLtp9ncvo08bWEYYZonKJ5FvVw9+jgXiwIDAQAB
          -----END PUBLIC KEY-----

druid1:
  url: jdbc:mysql://127.0.0.1:3306/sprssoZdemo1?useUnicode=true&characterEncoding=utf-8
  username: user1
  password: aaa
  driver-class: com.mysql.jdbc.Driver
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    sprssozdemo1: DEBUG