server:
  port: 9110
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: sprcld-prvdres1    # 项目名称尽量用小写

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true

myOauthServer: 
  #hostUrl: http://localhost
  hostUrl: http://localhost:8080
  #logoutUrl: ${myOauthServer.hostUrl}/signout
  logoutUrl: ${myOauthServer.hostUrl}/logreg/logout
  # directly to some1 oauth server /logout FAIL to logout
security:
  oauth2:
    resource:
      jwt:
        keyUri: ${myOauthServer.hostUrl}/oauth/token_key
        keyValue: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAjWx7waAGOW0GCvWtz22C0r2S9IDpjpURZiUbX9DFgUBSJ2/XqHYWP3I/I8IAWIvLqaE4RFAAwzaIySVN/pM2WUVRPCHlRF192HtrAc3CoZD5lVOHsU5f++22N6CrjQJQkX4V88efI596TbzqYkNJzmNLeBKuip9MLlMTW6z7+wuIw3KOUGk3+nH8MspMUk7vrGFOZG+UslkYCnx6+1gInEddaZm5HHyvAUh/lo7At3a2g7TaYE3PepSpZsZ6YNw68YhOkI+xG2OFkLek1vej8bGz6wEubeYI4nI3fjm8pEqh1s0NJrHwrxLtp9ncvo08bWEYYZonKJ5FvVw9+jgXiwIDAQAB
          -----END PUBLIC KEY-----

druid1:
  url: jdbc:mysql://127.0.0.1:3306/sprssoZdemo1?useUnicode=true&characterEncoding=utf-8
  username: user1
  password: aaa
  driver-class: com.mysql.jdbc.Driver
  initial-size: 1
  min-idle: 1
  max-active: 20
  test-on-borrow: true

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework: INFO
    sprssozdemo1: DEBUG